### ISSUE TITLE
instance variables in Opal JS templates lead to error

### ISSUE THREAD

**Issue by cantonic** [opal/opal-rails#44]
```ruby
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end
```

When you make a javascript call to `PostsControler#show`, `@post` should be available in `app/views/posts/show.js.opal`, but for me it leads to a `Stack level too deep` error.

Transcripts from https://gitter.im/opal/opal:

> **cantonic**: is the stack level too deep error happening because the template handler tries to transform the instance variables and all their methods etc into json? If so, could we change the template handler to perform to_json only on the instances attributes? or maybe even totally remove the instances from automatically being available and instead pass local variables to the js.opal file if necessary?

> **elia**: simplest solution would be to set those vars only when needed by the view, but that's probably my hate for passing data via ivars that's talking here
otherwise we could try to detect if they're used in the view
hackish but probably do-able
last option–which i don't like– would be to make it a config flag

> **cantonic**: I like the first solution. saves resources, even though one could expect view templates to have access to ivars since they are also available in html or js.erb template views.
elia: for the first solution the only problem would be detecting locals, but probably if locals are set we can trust it's done intentionally

From my logs:

```
SystemStackError - stack level too deep:
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `each'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:50:in `as_json'
  ... repeating hundreds of times...
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `each'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:50:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `each'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:50:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:140:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `each'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:50:in `as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `each'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `map'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:159:in `as_json'
  activesupport (4.1.9) lib/active_support/json/encoding.rb:34:in `encode'
  activesupport (4.1.9) lib/active_support/json/encoding.rb:21:in `encode'
  activesupport (4.1.9) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  app/views/drive/directories/create.js.opal:1:in `_app_views_drive_directories_create_js_opal___368000449424496302_70114515301600'
  actionview (4.1.9) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.9) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.9) lib/action_view/template.rb:143:in `render'
  xray-rails (0.1.14) lib/xray/engine.rb:33:in `render_with_xray'
  actionview (4.1.9) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.9) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.9) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.9) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.9) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.9) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.9) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.9) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.9) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.9) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.9) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.9) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.9) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.9) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.9) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.9) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.9) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/cantonic/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.1.9) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.9) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:40:in `render'
  app/controllers/drive/directories_controller.rb:31:in `create'
  actionpack (4.1.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.9) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.9) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.9) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.9) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.9) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.9) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.9) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.9) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.9) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.9) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.9) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.9) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.9) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.9) lib/action_dispatch/routing/route_set.rb:685:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  xray-rails (0.1.14) lib/xray/middleware.rb:37:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  jquery-fileupload-rails (0.4.4) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
  jquery-fileupload-rails (0.4.4) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/flash.rb:254:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.9) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.9) lib/active_record/migration.rb:380:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.9) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.1.9) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.9) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.9) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.9) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.9) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activesupport (4.1.9) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.9) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.1.9) lib/rails/engine.rb:514:in `call'
  railties (4.1.9) lib/rails/application.rb:144:in `call'
  newrelic_rpm (3.9.6.257) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/cantonic/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/cantonic/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/cantonic/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by elia** [comment]
iirc we discovered that the looping method was actually `to_json` and not opal-specific code.

I'll close this, but let me know if my memory is failing me.

**Comment by lorefnon** [comment]
Encountered while attempting to use `opal-rails` along with `activeadmin`. 

```ruby
  collection_action :some_action do
    render 'admin/questions/some_opal_template'
  end
```

After following the previous discussion I realize this fails because there is an instance variable `@current_tab`  which has recursive references `@current_tab -> @parent -> @children`. However this controller is provided by the gem and so is the instance variable.

Would it be acceptable if I send a PR for making serialization of ivars optional through a configuration option (at controller level and global level) ? 

Currently I have the following monkey patch in place to hold things together: 

```ruby
Opal::Rails::TemplateHandler.class_eval do

  def call(template)
    escaped = template.source.gsub(':', '\:')
    string = '%q:' + escaped + ':'
    "Opal.compile('Object.new.instance_eval {' << #{local_assigns} << #{string} << '}')"
  end

end
```

**Comment by elia** [comment]
> Would it be acceptable if I send a PR for making serialization of ivars optional through a configuration option (at controller level and global level) ?

Yes!

Be aware that master is now way different from the released version, which is tracked by the `0-8-stable` branch. Feel free to target that branch or both 🙂

**Comment by lorefnon** [comment]
@elia I have a functional [implementation](https://github.com/opal/opal-rails/pull/79) targeting master. Do let me know if there is something you would like me to improve on.
