### ISSUE TITLE
Rails generators fail if the application is named 'Opal'

### ISSUE THREAD

**Issue by henrebotha** [opal/opal-rails#92]
This was a head-scratcher!

```shell
$ bin/rails g controller HelloWorld index
/Users/henrebotha/dev/opal/config/application.rb:10:in `<module:Opal>': uninitialized constant Opal::Rails::Application (NameError)
        from /Users/henrebotha/dev/opal/config/application.rb:9:in `<top (required)>'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/henrebotha/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

I was following the Rails install tutorial from [here](http://opalrb.org/), and chose to name my app "Opal".

**Comment by elia** [comment]
You can probably fix it by changing `application.rb` as follows:

```rb
module Opal
  class Application < ::Rails::Application
    # …
```

But I advise against naming your app the same as any of the libraries you use.

---

I'll close this issue as it's not supported to have opal-rails work with apps using `Opal` as their namespace, but feel free to ask if you need any more help to make it work 🙂
